#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          wso2:
#            client-name: HungThinh Id
#            client-id: <client_id>
#            client-secret: <client_secret>
#            redirect-uri: <redirect-uri>
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          wso2:
#            token-uri: https://htid.hungthinhcorp.com.vn/oauth2/token
#            user-info-uri: https://htid.hungthinhcorp.com.vn/oauth2/userinfo
#            jwk-set-uri: https://htid.hungthinhcorp.com.vn/oauth2/jwks
#            authorization-uri: https://htid.hungthinhcorp.com.vn/oauth2/authorize